id: AAB90AA16
title: The Three Statements that Strike the Vital Point
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:15:42.075428
  last_modified_at: 2022-03-01 02:15:42.075432
